### ISSUE TITLE
[future]能不能添加一个功能

### ISSUE THREAD

**Issue by Zyilin98** [mrwoowoo/ruijie_login#2]
某些学校的锐捷认证的时候 需要指定服务 对应到就是`service=` 这个参数 
具体这个参数传到后面是 前端文字 例如 `中国移动` 经过两次UrlEncode编码之后返回的值 就是 `%25E4%25B8%25AD%25E5%259B%25BD%25E7%25A7%25BB%25E5%258A%25A8`
传到后面 `service=%25E4%25B8%25AD%25E5%259B%25BD%25E7%25A7%25BB%25E5%258A%25A8`
因为我不怎么熟悉c++ 所以大佬能不能加一个在登陆的时候指定service 的参数(？)
大概启动命令改为 ./文件名 账号 密码 service
service 这个值可以直接写我们自己手动转码后的  程序只做传递就行

**Comment by oakboat** [comment]
修改完成，因为中文会乱码的原因，service的值要给urlencode编码后的
